---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  # Git style
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-vcs-permalinks
  - id: forbid-new-submodules
  - id: no-commit-to-branch

  # Common errors
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    exclude: .gitlab-ci.yml
    # exclude: |
    #           (?x)^(
    #               README.md|
    #               .gitlab-ci.yml
    #           )$
  - id: check-yaml
  - id: check-merge-conflict
  # BUG: Currently detects README.md as executable
  # - id: check-executables-have-shebangs
  - id: check-symlinks
  - id: check-json

  # Cross platform
  - id: check-case-conflict
  - id: mixed-line-ending
    args: [--fix=lf]

  # Security
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']
  - id: detect-private-key

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.74.1
  hooks:
  - id: terraform_fmt
  - id: terraform_docs

# - repo: https://github.com/jumanjihouse/pre-commit-hooks
#   rev: 2.1.6
#   hooks:
#     - id: shfmt
#       args: ['-l', '-i', '2', '-ci', '-sr', '-w']
#     - id: shellcheck

# Dockerfile linter
- repo: https://github.com/hadolint/hadolint
  rev: v2.10.0
  hooks:
  - id: hadolint
    args: [
      '--ignore', 'DL3027', # Ignore Do not use apt
      '--ignore', 'DL3007', # Ignore Using latest
      '--ignore', 'DL4006', # Ignore Not related to alpine
      '--ignore', 'SC1091', # Ignore Useless check
      '--ignore', 'SC2015', # Ignore Useless check
      '--ignore', 'SC3037', # Ignore Not related to alpine
      '--ignore', 'DL3013', # Ignore Pin versions in pip
      '--ignore', 'DL3008', # Ignore Pin versions in apt get install
      '--ignore', 'DL3009', # Ignore Delete the apt-get lists after installing something'
      '--ignore', 'DL3015', # Ignore Avoid additional packages by specifying `--no-install-recommends`
      '--ignore', 'DL3003', # Ignore WORKSPACE to switch directory
      '--ignore', 'DL3059', # Ignore Multiple RUN Commands
      '--ignore', 'SC2155', # Ignore Declare and assign separately to avoid masking return values.'
    ]
